Update dotfiles

diff --git a/bin/dot-link-files b/bin/dot-link-files
--- a/bin/dot-link-files
+++ b/bin/dot-link-files
@@ -1,22 +1,36 @@
 #!/usr/bin/env bash
 
-dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd); dir=$(dirname $dir)
+if [ -z "$DOTFILES_PATH" ]; then
+  echo 'Abort: Expected $DOTFILES_PATH to be set'
+  exit 1
+fi
 
+# Hidden files
 declare -a files=(
-    bash_profile
-    gitconfig
-    gitignore
-    eslintrc
-    inputrc
-    tmux.conf
-    vim
-    vimrc
-    ctags
-    replyrc
-    gemrc
+  gitconfig
+  gitignore
+  eslintrc
+  inputrc
+  tmux.conf
+  vim
+  vimrc
+  replyrc
+  prettier
+  gemrc
+  ripgreprc
 )
 
 for i in ${files[@]}; do
-    # create symbolic link if not exists
-    [ -L $HOME/.$i ] || ln -sv $dir/$i $HOME/.$i
+  # create symbolic link if not exists
+  [ -L $HOME/.$i ] || ln -sv $DOTFILES_PATH/$i $HOME/.$i
+done
+
+# Normal files
+declare -a files=(
+  tsconfig.json
+)
+
+for i in ${files[@]}; do
+  # create symbolic link if not exists
+  [ -L $HOME/$i ] || ln -sv $DOTFILES_PATH/$i $HOME/$i
 done
